@extends('cpanel.layout')
@section('content')


   <div class="col-lg-9 col-md-12 col-sm-12 mainContent">
       <div class="panel panel-default">
            <div class="panel-heading">
                    <h4 class="panel-title">{{ $title}}</h4>
            </div>

            <div class="panel-body">

              <!--start content -->

@if(count($ib_accounts)<1)
<h3>You Don't Have Any IB Accounts</h3>
@else


	<h4>What's "My Referral Link"?</h4>
	<p>My Referral Link is a unique link generated by our system that identifies who you are. This way, we can give you credit when a friend or colleague becomes a Constant Contact customer.</p>

	<p>Here's how you can use your unique referral link:</p>
	<ul>
		<li>Copy and send the link in a regular personal email.</li>
		<li>Include the link in your email signature.</li>
		<li>Place the link on your website for your site visitors.</li>
	</ul>


	<p>No matter how you share, be sure to have your friend click on your specific link so we can make sure that you get the credit. If they then become Constant Contact customers, you both get account credits!</p>


<input class="form-control" id="MyRef" value="https://www.jmibrokers.com/en/signup?myref={{$user->id+10000}}" style="background:#ddd;" /><br />
<button onclick="CopyText()" class="btn btn-success">Copy Link</button>

<script type="text/javascript">
	function CopyText()
	{
	$('input#MyRef').val('https://www.jmibrokers.com/en/signup?myref={{$user->id+10000}}');
	var copyText = document.getElementById("MyRef");
  	copyText.select();
  	document.execCommand("Copy");
	}
</script>





@endif


    </div>

</div>



       <!--End content-->
            </div>
        </div>

    </div>

@stop
